management:
  endpoints:
    web:
      exposure:
        include: health, metrics
      base-path: /meta
  info:
    git:
      mode: full


spring:
  jmx:
    enabled: false
  cloud:
    consul:
      discovery:
        health-check-path: /meta/health

api:
  base-path: api
  ignored:
    - /meta/health
    - /meta/metrics
    - /webjars/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /validatorUrl
    - /v2/api-docs
